# Pasted from https://github.com/francesconicoletta/toolbox/tree/f9a08d3548b55231180e132d0e091138acc99a21/images/ubuntu/20.04
FROM docker.io/library/ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

ENV NAME=ubuntu-toolbox VERSION=20.04
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Gavus personalized image for Ubuntu toolbox containers" \
      maintainer="Gustav Johansson <gustavsj@outlook.com>"

COPY _readme.md /README.md

RUN apt-get update

COPY missing-docs /
RUN apt-get -y reinstall $(cat missing-docs)
RUN rm /missing-docs

COPY extra-packages /
RUN apt-get -y install $(cat extra-packages)
RUN rm /extra-packages

RUN apt-get clean

COPY exempt_group /etc/sudoers.d/

CMD /bin/sh

